# Site
name: "Coinsence"
title: "Coinsence"
description: "Enabling people :seedling:"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
url: 'https://coinsence.github.io'
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
community_url: 'https://community.coinsence.org'
about_url: 'https://coinsence.org/#about'
with_featured: false
with_categories: false

# Authors
authors:
  craxrev:
    name: Mortadha
    display_name: Mortadha
    gravatar: 9c67e3fa9e2fe00b9d99914ccdb371fe
    email: mortadha.ghanmi56@gmail.com
    web: https://example.com
    twitter: https://twitter.com/gmor93
    description: "Fullstack developer and a GameR :bowtie:"
  seif:
    name: Seif
    display_name: Seif
    gravatar: 6f38e9be18cee5e9e24e542d0ffd3b30
    email: Seif@coinsence.org
    web: https://www.linkedin.com/in/seif-badri
    twitter: https://twitter.com/badri_seif
    description: "Alternative economy and blockchain enthusiast"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jemoji

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-xxxxxxxxxxxxxxxx"
adsense-data-ad-slot: "xxxxxxxxxx"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]