# Site
name: "Coinsence"
title: "Coinsence"
description: "Enabling people :seedling:"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
url: 'https://coinsence.github.io'
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
community_url: 'https://community.coinsence.org'
about_url: 'https://coinsence.org/#about'
with_featured: false
with_categories: false

# Authors
authors:
  team:
    name: team
    display_name: Coinsence team
    avatar: 'assets/images/avatars/team.png'
    email: info@coinsence.org
    web: https://coinsence.org
    twitter: https://community.coinsence.org
    description: "A thriving community of change makers connected via Coinsence.org to empower everyone through blockchain based community currencies."
  seif:
    name: Seif
    display_name: Seif
    gravatar: 6f38e9be18cee5e9e24e542d0ffd3b30
    email: Seif@coinsence.org
    web: https://www.linkedin.com/in/seif-badri
    twitter: https://twitter.com/badri_seif
    description: "Alternative economy and blockchain enthusiast"
  sarra:
    name: Sarra
    display_name: Sarra turki
    avatar: 'assets/images/avatars/sarra.jpg'
    email: sara04240@gmail.com
    web: https://www.linkedin.com/in/sarra-turki-909193b1/
    twitter: https://www.facebook.com/sara.turki.165
    description: "A recent graduate in IR studies with a special interest in the socio-economic development in the African Continent."
  karim:
    name: Karim
    display_name: Karim Chabrak
    avatar: 'assets/images/avatars/Karim.jpg'
    email: karim@coinsence.org
    web: https://www.linkedin.com/in/karim-chabrak-57815677
    description: "Founder Coinsence.org"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jemoji

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-xxxxxxxxxxxxxxxx"
adsense-data-ad-slot: "xxxxxxxxxx"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
