# Site
name: "Coinsence"
title: "Coinsence"
description: "Enabling people :seedling:"
meta_description: "Enabling people, community collaboration, Create shared value."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
url: 'https://coinsence.github.io'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  craxrev:
    name: Mortadha
    display_name: Mortadha
    gravatar: 9c67e3fa9e2fe00b9d99914ccdb371fe
    email: mortadha.ghanmi56@gmail.com
    web: https://example.com
    twitter: https://twitter.com/gmor93
    description: "All hail His Grace, Mortadha of House Ghanmi, First of His Name, King of the Sandals and the First Men, Lord of the Seven Kingdoms, and Protector of the Realm. :joy: :joy: :joy:"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jemoji

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
